/* SchoolMate — UI library barrel */
export { Icon } from './Icon'
export type { IconProps } from './Icon'
export { Btn, IconBtn, Badge, TierPill, Avatar, Progress, Skeleton, Spinner } from './primitives'
export type { BtnProps, IconBtnProps, BadgeTone } from './primitives'
export { Field, Input, Textarea, Select, Toggle, Checkbox, Search } from './forms'
export type { InputProps, TextareaProps, SelectProps, SelectOption } from './forms'
export { Tabs, Segmented, Breadcrumb, Popover, MenuItem, MenuSep, MenuLabel } from './nav'
export type { TabItem, SegItem, Crumb } from './nav'
export { Modal, Drawer, Tip } from './overlay'
export { Card, CardHead, Empty, Kpi, PageHead } from './content'
export { Spark, Donut, Bars, HBars, LineChart, Legend, Gauge } from '@/components/charts/Charts'
export type { Segment, Series, BarDatum } from '@/components/charts/Charts'
export { DataTable } from '@/components/table/DataTable'
export type { Column } from '@/components/table/DataTable'
